### ISSUE TITLE
Parent stacking context not working?

### ISSUE THREAD

**Issue by OliverJAsh** [gwwar/z-context#13] opened 2019-10-18 10:50 UTC
E.g. https://output.jsbin.com/zovecuzoce/1

```html
<div class="absolute">
    <div class="relative">
        <div class="child">foo</div>
    </div>
</div>
```

```css
.absolute {
    position: absolute;
}

.relative {
    position: relative;
}
```

When selecting `.relative`:

![image](https://user-images.githubusercontent.com/921609/67088537-4cabd580-f19d-11e9-97b6-cd92e41e7955.png)

Expected parent stacking context: `.absolute`

When selecting `.child`:

![image](https://user-images.githubusercontent.com/921609/67088543-503f5c80-f19d-11e9-89ff-5f2e5f77b4ae.png)

Expected parent stacking context: `.relative`

**Comment by litera** [comment] 2019-12-11 22:33
This seems to be correct, because both of your container divs are merely positioned, but they don't create a stacking context. As per [specification](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context):

> *Element with a `position` value `absolute` or `relative` **and** `z-index` value other than `auto`.*

None of your positioned elements set `z-index` which means that the value is `auto`, resulting in no new stacking context. So their parent stacking context is still HTML root element.
But if your two container elements would have either `sticky` or `fixed`, they would create a stacking context, because for such positioned elements, `z-index` is irrelevant.

This is therefore not a bug and issue can be easily **closed**.

**Comment by OliverJAsh** [comment] 2019-12-11 23:36
Ah that makes sense, thank you.

Off the back of that, a suggestion: it would be great if this extension could show you which parent an element is positioned relative to (when there is no z-index). Although I realise that might be out of scope

**Comment by OliverJAsh** [comment] 2019-12-12 11:29
Testing with "Edinburgh, UK"

![Screen Recording 2019-12-12 at 11 26 15](https://user-images.githubusercontent.com/921609/70708521-a084f780-1cd2-11ea-8516-6d61fb8f97f7.gif)

**Comment by litera** [comment] 2019-12-12 12:02
> Off the back of that, a suggestion: it would be great if this extension could show you which parent an element is positioned relative to (when there is no z-index). Although I realise that might be out of scope

I agree. Displaying *current* is irrelevant, because you can see which element is being selected in the tree. And as you suggested, parent stacking context element could simply be referenced there instead of the extension calling `generateSelector` on it. Maybe the author @gwwar can simplify the code a bit, to do just that.

**Comment by OliverJAsh** [comment] 2020-06-05 08:29
A made a separate Chrome extension for this: https://twitter.com/OliverJAsh/status/1268821858842968065

**Comment by gwwar** [comment] 2021-11-02 18:54
Glad you find a solution! I'll close this one out, but will document the `current` feedback in #20.

**Closed as completed by gwwar** 2021-11-02 18:54 UTC
