### ISSUE TITLE
Z-index tab shows 'No properties'

### ISSUE THREAD

**Issue by AlexBazer** [gwwar/z-context#11] opened 2018-09-20 08:47 UTC
Z-index tabs sows 'No properties' on any DOM element
![debug toolbar screenshot](https://image.ibb.co/mRmxjz/Screenshot_from_2018_09_20_10_36_51.png)

Observe same behavior on chrome 69 and chromium 68.

**Comment by Jehong-Ahn** [comment] 2020-10-28 02:19
I have no problem on chrome 86.

**Comment by daiplusplus** [comment] 2021-08-12 21:38
I also get a blank Z-index tab in Chrome 92:

![image](https://user-images.githubusercontent.com/1693078/129273516-b369c0d9-267c-49b2-8401-5514b70f2fca.png)

**Comment by Jehong-Ahn** [comment] 2021-08-13 01:16
I have a blank tab ,too. On chrome 92.

**Comment by ukrutt** [comment] 2021-08-17 21:26
Same, Chrome 92.  (And it worked until recently.)

**Comment by daiplusplus** [comment] 2021-08-17 21:29
Methinks the new issue we're experiencing in Chrome 92 is not the same as originally reported in 2018...

It's too late now to create a new issue and move the 2 new replies, but  @AlexBazer if you're still around, can you rename this issue to "Z-index tab not loading in Chrome 92"?

**Comment by gwwar** [comment] 2021-11-02 19:03
Are folks still seeing this in Chrome 95? ~Note that I haven't found a solution for content in iframe yet https://github.com/gwwar/z-context/issues/5~ Edit: I've fixed the iframe issue

**Comment by shawninder** [comment] 2022-01-13 00:37
@gwwar I'm still getting an empty Z-Index pane for all elements on Chrome 97 on mac (Mojave)

**Comment by gwwar** [comment] 2022-01-13 15:17
@shawninder thanks for adding a report. I'm on Mojave and Chrome 97.0.4692.71 and I've unfortunately haven't been able to reproduce this yet.

If folks are interested here are a few steps to try:
#### Reload the browser
- If the extension has just been installed, try fully closing the browser and reopening it.
#### See if errors are being thrown in certain environments
- If folks have the time, it's possible to load the extension in developer mode using the code in this repository (no build step needed).
- `git clone https://github.com/gwwar/z-context.git`
- Visit `chrome://extensions/`
- Click on "load unpacked" and select the z-context folder
- Then click on the inspect views link to open an inspection window (another dev console to see if any errors occur).
- We can then visit a page like https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context to inspect elements using the Z-index panel
- Take a screenshot if any errors are thrown in the inspection window. I can try and troubleshoot further/bulletproof from there.


| enable developer mode | load unpacked |
|-----|-----|
| ![enable developer mode](https://user-images.githubusercontent.com/1270189/149356958-7eeb0c2b-7b5f-4519-9e42-8b0dc3bae270.png) | ![load unpacked](https://user-images.githubusercontent.com/1270189/149357049-5963565a-b53f-4c21-8a04-fe4c7182a9d7.png) |

**Comment by Andrey-Svetlichny** [comment] 2022-01-26 08:24
@gwwar thank you for your effort
I'm getting an empty Z-Index pane for all elements on Chrome 97 - Windows

loaded extension in dev mode - no errors
**empty Z-Index pane** for react app on localhost
**working** on https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

by the way, clone link broken, correct link:
`git clone https://github.com/gwwar/z-context.git`

**Comment by gwwar** [comment] 2022-01-26 16:30
> empty Z-Index pane for react app on localhost

Nice @Andrey-Svetlichny, with the previous manifest file we'd only inject the extension scripts on pages with the https:// protocol. In #23 I've also included the http protocol. 

I'll keep this issue open until a new extension version is accepted by Chrome.

**Comment by gwwar** [comment] 2022-01-26 17:00
v2.1.0 has been submitted for review. It may take a few days to get an approval or rejection. If folks are blocked, you can use steps in https://github.com/gwwar/z-context/issues/11#issuecomment-1012232133 to run the latest version locally

**Comment by gwwar** [comment] 2022-01-31 22:20
Looks like v2.1.0 was accepted. I'm closing this issue for now, but if folks see a similar issue, let's open a new ticket.

**Closed as completed by gwwar** 2022-01-31 22:20 UTC
